project:
  type: book
  output-dir: docs

book:
  title: "EDAV Final Project"
  author: "Norah Jones"
  date: "11/5/2023"
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo


